apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mediacms-service: mediabeat
  name: mediabeat
spec:
  replicas: 1
  selector:
    matchLabels:
      mediacms-service: mediabeat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mediacms-service: mediabeat
        user: mediacms
    spec:
      securityContext:
        runAsUser: 80
        runAsGroup: 80
        fsGroup: 80
        fsGroupChangePolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
        - env:
            - name: ENABLE_CELERY_LONG
              value: "no"
            - name: ENABLE_CELERY_SHORT
              value: "no"
            - name: ENABLE_CELERY_BEAT
              value: "yes"
            - name: ENABLE_MIGRATIONS
              value: "no"
            - name: ENABLE_NGINX
              value: "no"
            - name: ENABLE_UWSGI
              value: "no"
              value: "mediacms"
            - name: HOME_SERVER
              value: "10.2.0.18"
            - name: PUBLIC_HOME_SERVER
              value: "silo5.sciencedata.dk"
          image: sciencedata/mediacms_sciencedata:latest
          name: mediabeat
          volumeMounts:
            - name: nfs-claim-sciencedata-mediacms
              mountPath: /home/mediacms.io/mediacms/media_files
              readOnly: false
      restartPolicy: Always
      volumes:
        - configMap:
            name: mediabeat-cm0
          name: mediabeat-cm0
