apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mediacms-service: celery-beat
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      mediacms-service: celery-beat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mediacms-service: celery-beat
        user: mediacms
    spec:
      containers:
        - env:
            - name: ENABLE_CELERY_LONG
              value: "no"
            - name: ENABLE_CELERY_SHORT
              value: "no"
            - name: ENABLE_CELERY_BEAT
              value: "yes"
            - name: ENABLE_MIGRATIONS
              value: "no"
            - name: ENABLE_NGINX
              value: "no"
            - name: ENABLE_UWSGI
              value: "no"
          image: mediacms/mediacms:latest
          name: celery-beat
          volumeMounts:
            - name: nfs-claim-sciencedata-mediacms
              mountPath: /home/mediacms.io/mediacms
              readOnly: false
      restartPolicy: Always
      volumes:
        - configMap:
            name: celery-beat-cm0
          name: celery-beat-cm0
