apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mediacms-service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      mediacms-service: celery-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mediacms-service: celery-worker
    spec:
      containers:
        - env:
            - name: ENABLE_CELERY_BEAT
              value: "no"
            - name: ENABLE_MIGRATIONS
              value: "no"
            - name: ENABLE_NGINX
              value: "no"
            - name: ENABLE_UWSGI
              value: "no"
          image: mediacms/mediacms:latest
          name: celery-worker
          volumeMounts:
            - name: nfs-claim-sciencedata-mediacms
              mountPath: /home/mediacms.io/mediacms
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: nfs-claim-sciencedata-mediacms
          persistentVolumeClaim:
            claimName: nfs-claim-10.0.0.18-mediacms
