apiVersion: v1
kind: Pod
metadata:
  labels:
    mediacms-service: migrations
  name: migrations
spec:
  containers:
    - args:
        - ./deploy/docker/prestart.sh
      env:
        - name: ADMIN_EMAIL
          value: admin@localhost
        - name: ADMIN_USER
          value: admin
        - name: ENABLE_CELERY_BEAT
          value: "no"
        - name: ENABLE_CELERY_LONG
          value: "no"
        - name: ENABLE_CELERY_SHORT
          value: "no"
        - name: ENABLE_NGINX
          value: "no"
        - name: ENABLE_UWSGI
          value: "no"
      image: mediacms/mediacms:latest
      name: migrations
      volumeMounts:
        - name: nfs-claim-sciencedata-mediacms
          mountPath: /home/mediacms.io/mediacms
          readOnly: false
  restartPolicy: OnFailure
  volumes:
    - name: nfs-claim-sciencedata-mediacms
      persistentVolumeClaim:
        claimName: nfs-claim-10.0.0.18-mediacms
