apiVersion: v1
kind: Service
metadata:
  labels:
    mediacms-service: mediaweb
  name: mediaweb
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    mediacms-service: mediaweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mediacms-service: mediaweb
  name: mediaweb
spec:
  replicas: 1
  selector:
    matchLabels:
      mediacms-service: mediaweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mediacms-service: mediaweb
    spec:
      containers:
        - env:
            - name: ENABLE_CELERY_BEAT
              value: "no"
            - name: ENABLE_CELERY_LONG
              value: "no"
            - name: ENABLE_CELERY_SHORT
              value: "no"
            - name: ENABLE_MIGRATIONS
              value: "no"
          image: mediacms/mediacms:latest
          name: mediaweb
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nfs-claim-sciencedata-mediacms
              mountPath: /home/mediacms.io/media_files
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: nfs-claim-sciencedata-mediacms
          persistentVolumeClaim:
            claimName: nfs-claim-10.0.0.18-mediacms

