apiVersion: v1
kind: Service
metadata:
  labels:
    mediacms-service: mediaweb1
  name: mediaweb1
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    mediacms-service: mediaweb1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mediacms-service: mediaweb1
  name: mediaweb1
spec:
  replicas: 1
  selector:
    matchLabels:
      mediacms-service: mediaweb1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mediacms-service: mediaweb1
        user: mediacms
    spec:
      securityContext:
        runAsUser: 80
        runAsGroup: 80
        fsGroup: 80
        fsGroupChangePolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
        - env:
            - name: ENABLE_UWSGI
              value: "yes"
            - name: ENABLE_NGINX
              value: "yes"
            - name: ENABLE_CELERY_BEAT
              value: "no"
            - name: ENABLE_CELERY_LONG
              value: "no"
            - name: ENABLE_CELERY_SHORT
              value: "no"
            - name: ENABLE_MIGRATIONS
              value: "no"
            - name: EMAIL_HOST_PASSWORD
              value: ""
            - name: SD_UID
              value: "mediacms"
            - name: HOME_SERVER
              value: "10.2.0.18"
            - name: PUBLIC_HOME_SERVER
              value: "silo5.sciencedata.dk"
            - name: REDIS_HOST
              value: "mediaredis1"
            - name: NO_SAML
              value: "yes"
          image: sciencedata/mediacms_sciencedata:latest
          name: mediaweb1
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: nfs-claim-sciencedata-mediacms
              mountPath: /home/mediacms.io/mediacms/media_files
              readOnly: false
          securityContext:
            capabilities:
              add:
              - SYS_CHROOT
              - AUDIT_WRITE
              - NET_ADMIN
      restartPolicy: Always
      volumes:
        - name: nfs-claim-sciencedata-mediacms
          persistentVolumeClaim:
            claimName: nfs-claim-10.0.0.18-mediacms

