apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mediacms-service: mediaworker1
  name: mediaworker1
spec:
  replicas: 1
  selector:
    matchLabels:
      mediacms-service: mediaworker1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        mediacms-service: mediaworker1
        user: mediacms
    spec:
      securityContext:
        runAsUser: 80
        runAsGroup: 80
        fsGroup: 80
        fsGroupChangePolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
        - env:
            - name: ENABLE_UWSGI
              value: "no"
            - name: ENABLE_NGINX
              value: "no"
            - name: ENABLE_CELERY_BEAT
              value: "no"
            - name: ENABLE_CELERY_LONG
              value: "yes"
            - name: ENABLE_CELERY_SHORT
              value: "yes"
            - name: ENABLE_MIGRATIONS
              value: "no"
              value: "mediacms"
            - name: HOME_SERVER
              value: "10.2.0.18"
            - name: PUBLIC_HOME_SERVER
              value: "silo5.sciencedata.dk"
            - name: REDIS_HOST
              value: "mediaredis1"
            - name: CUDA_VISIBLE_DEVICES_NUM
              value: "4"
          image: sciencedata/mediacms-worker_sciencedata:latest
          name: mediaworker1
          volumeMounts:
            - name: nfs-claim-sciencedata-mediacms
              mountPath: /home/mediacms.io/mediacms/media_files
              readOnly: false
          resources:
            limits:
              nvidia.com/gpu: 4
          securityContext:
            capabilities:
              add:
                - "SYS_CHROOT"
                - "AUDIT_WRITE"
                - "NET_ADMIN"
      runtimeClassName: nvidia
      nodeName: worker1
      restartPolicy: Always
      volumes:
        - name: nfs-claim-sciencedata-mediacms
          persistentVolumeClaim:
            claimName: nfs-claim-10.0.0.18-mediacms
